<?php
/**
 * Classic tours: Madrid, Barcelona (Gaudí), Rome (Colosseum→Trevi).
 * Included by create_all_tours.php — appends to $tours array.
 */

// ============================================================
// TOUR — MADRID: Historic Madrid — From the Royal Palace to the Prado
// ============================================================
$tours[] = [
  'title'       => 'Historic Madrid: From the Royal Palace to the Prado',
  'description' => 'Discover the heart of Spain\'s capital on this immersive walking tour through Madrid\'s most iconic historic district. Starting at the majestic Royal Palace — one of the largest in Europe — you\'ll journey through centuries of Spanish history, art, and culture. Along the way you\'ll cross the legendary Plaza Mayor, explore the vibrant streets of La Latina, and finish at the world-renowned Museo del Prado, home to masterpieces by Velázquez, Goya, and El Greco. This tour is perfect for first-time visitors and history enthusiasts alike. Comfortable walking shoes are recommended as the route covers approximately 4 kilometres of cobblestone streets and historic plazas.',
  'duration'    => 180,
  'country'     => 'Spain',
  'city'        => 'Madrid',
  'location'    => ['lat' => 40.4168, 'lng' => -3.7038],
  'translations' => [
    'es' => [
      'title'       => 'Madrid histórico: del Palacio Real al Prado',
      'description' => 'Descubra el corazón de la capital de España en esta ruta a pie por el casco histórico más icónico de Madrid. Desde el majestuoso Palacio Real — uno de los más grandes de Europa — recorrerá siglos de historia, arte y cultura española. Cruzará la legendaria Plaza Mayor, explorará las calles de La Latina y finalizará en el Museo del Prado, hogar de obras maestras de Velázquez, Goya y El Greco. Se recomienda calzado cómodo para los aproximadamente 4 kilómetros de calles adoquinadas.',
    ],
    'fr' => [
      'title'       => 'Madrid historique : du Palais Royal au Prado',
      'description' => 'Découvrez le cœur de la capitale espagnole lors de cette promenade immersive à travers le quartier historique le plus emblématique de Madrid. Du majestueux Palais Royal — l\'un des plus grands d\'Europe — vous traverserez des siècles d\'histoire, d\'art et de culture espagnols. Vous croiserez la légendaire Plaza Mayor, explorerez les rues de La Latina et terminerez au Museo del Prado, qui abrite des chefs-d\'œuvre de Velázquez, Goya et El Greco.',
    ],
    'de' => [
      'title'       => 'Historisches Madrid: Vom Königspalast zum Prado',
      'description' => 'Entdecken Sie das Herz der spanischen Hauptstadt auf diesem eindringlichen Spaziergang durch Madrids ikonischstes historisches Viertel. Vom majestätischen Königspalast — einem der größten Europas — wandern Sie durch Jahrhunderte spanischer Geschichte, Kunst und Kultur. Sie überqueren die legendäre Plaza Mayor, erkunden die Straßen von La Latina und enden im weltberühmten Museo del Prado mit Meisterwerken von Velázquez, Goya und El Greco.',
    ],
    'it' => [
      'title'       => 'Madrid storica: dal Palazzo Reale al Prado',
      'description' => 'Scoprite il cuore della capitale spagnola in questo percorso a piedi attraverso il quartiere storico più iconico di Madrid. Dal maestoso Palazzo Reale — uno dei più grandi d\'Europa — attraverserete secoli di storia, arte e cultura spagnola. Attraverserete la leggendaria Plaza Mayor, esplorerete le strade de La Latina e terminerete al Museo del Prado, che custodisce capolavori di Velázquez, Goya e El Greco.',
    ],
  ],
  'steps' => [
    [
      'title'       => 'Palacio Real — The Royal Palace',
      'order'       => 1,
      'location'    => ['lat' => 40.4179, 'lng' => -3.7143],
      'description' => 'Begin your journey at the Palacio Real de Madrid, the official residence of the Spanish Royal Family and one of the most impressive palaces in the world. Built in the 18th century under King Philip V on the ruins of a medieval Moorish castle, this breathtaking Baroque masterpiece contains over 3,400 rooms — although only around 50 are open to the public. As you approach through the Plaza de la Armería, take a moment to admire the sheer scale of the building: 135,000 square metres of floor space clad in limestone and granite. Inside, you\'ll find the Royal Armoury — one of the finest collections of arms and armour in Europe — along with the state dining room, the Throne Room lined in crimson velvet and gold leaf, and the extraordinary ceiling fresco by Giovanni Battista Tiepolo in the Royal Chapel. The palace faces west towards the Casa de Campo park, and on a clear day the views of the Guadarrama mountains from the Plaza de la Armería are simply unforgettable. Allow at least 45 minutes here. Audio guides are available at the entrance in 12 languages.',
      'translations' => [
        'es' => ['title' => 'Palacio Real — la residencia de los reyes', 'description' => 'Comience su recorrido en el Palacio Real de Madrid, residencia oficial de la Familia Real Española y uno de los palacios más impresionantes del mundo. Construido en el siglo XVIII bajo Felipe V sobre las ruinas de un alcázar medieval, esta obra maestra barroca contiene más de 3.400 estancias. Encontrará la Real Armería — una de las mejores colecciones de armas y armaduras de Europa — junto con el Salón del Trono forrado de terciopelo carmesí y pan de oro, y el extraordinario fresco de Tiepolo en la Capilla Real. Desde la Plaza de la Armería, las vistas de la Sierra de Guadarrama son inolvidables.'],
        'fr' => ['title' => 'Palacio Real — le Palais Royal', 'description' => 'Commencez votre parcours au Palacio Real de Madrid, résidence officielle de la Famille Royale espagnole et l\'un des palais les plus impressionnants au monde. Construit au XVIIIe siècle sous Philippe V sur les ruines d\'un château médiéval, ce chef-d\'œuvre baroque contient plus de 3 400 pièces. Vous y trouverez l\'Armurerie Royale, la Salle du Trône tapissée de velours cramoisi et de feuilles d\'or, et l\'extraordinaire fresque de Tiepolo dans la Chapelle Royale. Depuis la Plaza de la Armería, les vues sur la Sierra de Guadarrama sont inoubliables.'],
        'de' => ['title' => 'Palacio Real — der Königspalast', 'description' => 'Beginnen Sie Ihre Reise am Palacio Real de Madrid, der offiziellen Residenz der spanischen Königsfamilie und einem der beeindruckendsten Paläste der Welt. Im 18. Jahrhundert unter Philipp V. auf den Ruinen einer mittelalterlichen maurischen Burg erbaut, enthält dieses barocke Meisterwerk über 3.400 Räume. Sie finden die Königliche Rüstkammer, den Thronsaal mit purpurrotem Samt und Blattgold sowie das außergewöhnliche Deckenfresko von Tiepolo in der Königlichen Kapelle. Von der Plaza de la Armería bieten sich unvergessliche Ausblicke auf die Sierra de Guadarrama.'],
        'it' => ['title' => 'Palacio Real — il Palazzo Reale', 'description' => 'Iniziate il vostro percorso al Palacio Real de Madrid, residenza ufficiale della Famiglia Reale Spagnola e uno dei palazzi più impressionanti al mondo. Costruito nel XVIII secolo sotto Filippo V sulle rovine di un castello medievale moresco, questo capolavoro barocco contiene oltre 3.400 stanze. Troverete la Reale Armeria, la Sala del Trono rivestita in velluto cremisi e foglia d\'oro, e lo straordinario affresco del Tiepolo nella Cappella Reale. Dalla Plaza de la Armería, le viste sulla Sierra de Guadarrama sono indimenticabili.'],
      ],
    ],
    [
      'title'       => 'Catedral de la Almudena',
      'order'       => 2,
      'location'    => ['lat' => 40.4154, 'lng' => -3.7144],
      'description' => 'Just steps from the Royal Palace stands the Catedral de Santa María la Real de la Almudena, Madrid\'s cathedral and one of the most significant religious buildings in Spain. Its construction began in 1879 and wasn\'t completed until 1993 — over a century of work — making it one of the last great cathedrals built in Europe. The exterior blends Baroque and Neoclassical styles, designed to harmonise with the adjacent Royal Palace, while the interior surprises visitors with a striking neo-Gothic style featuring colourful modern stained glass windows commissioned in the 1990s. The cathedral houses the revered image of Our Lady of Almudena, patron saint of Madrid, whose origins date back to the reconquest of the city in 1083. Climb to the dome for panoramic views of the city and the Manzanares River valley — the small entrance fee is absolutely worth it. The crypt beneath the cathedral is also open to visitors and contains the tomb of José María Escrivá, founder of Opus Dei, who was canonised in 1992.',
      'translations' => [
        'es' => ['title' => 'Catedral de la Almudena', 'description' => 'A pocos pasos del Palacio Real se alza la Catedral de Santa María la Real de la Almudena, la catedral de Madrid y uno de los edificios religiosos más significativos de España. Su construcción comenzó en 1879 y no se completó hasta 1993 — más de un siglo de obras — convirtiéndola en una de las últimas grandes catedrales europeas. El exterior mezcla estilos barroco y neoclásico para armonizar con el Palacio Real. Alberga la venerada imagen de la Virgen de la Almudena, patrona de Madrid, cuya devoción se remonta a la reconquista de 1083. Suba a la cúpula para disfrutar de vistas panorámicas de la ciudad y del río Manzanares.'],
        'fr' => ['title' => 'La Cathédrale de l\'Almudena', 'description' => 'À quelques pas du Palais Royal se dresse la Cathédrale de l\'Almudena, la cathédrale de Madrid et l\'un des édifices religieux les plus importants d\'Espagne. Sa construction débuta en 1879 et ne s\'acheva qu\'en 1993 — plus d\'un siècle de travaux — ce qui en fait l\'une des dernières grandes cathédrales européennes. L\'extérieur mêle styles baroque et néoclassique pour s\'harmoniser avec le Palais Royal. Elle abrite la vénérée image de Notre-Dame de l\'Almudena, patronne de Madrid. Montez au dôme pour des vues panoramiques de la ville et de la vallée du Manzanares.'],
        'de' => ['title' => 'Kathedrale von Almudena', 'description' => 'Nur wenige Schritte vom Königspalast steht die Kathedrale von Almudena, Madrids Kathedrale und eines der bedeutendsten religiösen Bauwerke Spaniens. Ihr Bau begann 1879 und wurde erst 1993 vollendet — über ein Jahrhundert Bauzeit — was sie zu einer der letzten großen europäischen Kathedralen macht. Das Äußere verbindet Barock und Neoklassizismus, um mit dem Königspalast zu harmonieren. Sie beherbergt das verehrte Bildnis der Virgen de la Almudena, Schutzpatronin Madrids. Steigen Sie zur Kuppel hinauf für Panoramablicke über die Stadt und das Manzanares-Tal.'],
        'it' => ['title' => 'Cattedrale dell\'Almudena', 'description' => 'A pochi passi dal Palazzo Reale sorge la Cattedrale dell\'Almudena, la cattedrale di Madrid e uno degli edifici religiosi più significativi della Spagna. La costruzione iniziò nel 1879 e non fu completata fino al 1993 — oltre un secolo di lavori — rendendola una delle ultime grandi cattedrali europee. L\'esterno fonde stili barocco e neoclassico per armonizzarsi con il Palazzo Reale. Custodisce la venerata immagine della Vergine dell\'Almudena, patrona di Madrid. Salite alla cupola per viste panoramiche sulla città e sulla valle del Manzanares.'],
      ],
    ],
    [
      'title'       => 'Plaza Mayor — The Grand Square',
      'order'       => 3,
      'location'    => ['lat' => 40.4154, 'lng' => -3.7074],
      'description' => 'A ten-minute walk east from the cathedral brings you to one of Europe\'s most magnificent public squares: the Plaza Mayor. Constructed between 1617 and 1619 under King Philip III — whose equestrian statue stands proudly at its centre — this vast rectangular plaza measures 129 by 94 metres and is enclosed on all four sides by uniform Baroque buildings with 237 balconies overlooking the square. Throughout its 400-year history, Plaza Mayor has served as a marketplace, a bullfighting arena, a site for public executions during the Spanish Inquisition, and the setting for beatifications and royal celebrations. Today it is lined with traditional restaurants and cafés — be aware that prices here reflect the prime tourist location. For a more authentic and affordable experience, duck into one of the nine archways leading off the plaza into the surrounding streets of the historic centre. The square is particularly magical in the early morning before the crowds arrive, and in December when it hosts Madrid\'s famous Christmas market. Look up at the Casa de la Panadería on the north side — its elaborate allegorical frescoes were painted in 1992 and are a relatively recent addition to this centuries-old square.',
      'translations' => [
        'es' => ['title' => 'Plaza Mayor — la gran plaza', 'description' => 'A diez minutos a pie de la catedral se encuentra una de las plazas públicas más magníficas de Europa: la Plaza Mayor. Construida entre 1617 y 1619 bajo Felipe III — cuya estatua ecuestre preside el centro — esta vasta plaza rectangular mide 129 por 94 metros y está rodeada en sus cuatro lados por edificios barrocos uniformes con 237 balcones. A lo largo de sus 400 años de historia ha servido como mercado, plaza de toros, lugar de ejecuciones durante la Inquisición y escenario de beatificaciones. En diciembre acoge el famoso mercado navideño madrileño. Fíjese en la Casa de la Panadería al norte, con sus elaborados frescos alegóricos pintados en 1992.'],
        'fr' => ['title' => 'La Plaza Mayor — la grande place', 'description' => 'À dix minutes à pied de la cathédrale se trouve l\'une des places publiques les plus magnifiques d\'Europe : la Plaza Mayor. Construite entre 1617 et 1619 sous Philippe III — dont la statue équestre trône fièrement au centre — cette vaste place rectangulaire mesure 129 sur 94 mètres et est encadrée de bâtiments baroques uniformes avec 237 balcons. Elle a servi de marché, d\'arène de corrida, de lieu d\'exécutions de l\'Inquisition et de théâtre de célébrations royales au cours de ses 400 ans d\'histoire. En décembre, elle accueille le célèbre marché de Noël madrilène.'],
        'de' => ['title' => 'Plaza Mayor — der große Platz', 'description' => 'Zehn Gehminuten östlich der Kathedrale erreichen Sie einen der prächtigsten öffentlichen Plätze Europas: die Plaza Mayor. Zwischen 1617 und 1619 unter Philipp III. erbaut — dessen Reiterstatue im Zentrum steht — misst dieser riesige rechteckige Platz 129 mal 94 Meter und ist auf allen vier Seiten von einheitlichen Barockgebäuden mit 237 Balkonen umgeben. In 400 Jahren Geschichte diente er als Markt, Stierkampfarena, Hinrichtungsort der Inquisition und Schauplatz königlicher Feiern. Im Dezember findet hier Madrids berühmter Weihnachtsmarkt statt.'],
        'it' => ['title' => 'Plaza Mayor — la grande piazza', 'description' => 'A dieci minuti a piedi dalla cattedrale si trova una delle piazze pubbliche più magnifiche d\'Europa: la Plaza Mayor. Costruita tra il 1617 e il 1619 sotto Filippo III — la cui statua equestre svetta al centro — questa vasta piazza rettangolare misura 129 per 94 metri ed è racchiusa su tutti e quattro i lati da edifici barocchi uniformi con 237 balconi. Nei suoi 400 anni di storia è stata mercato, arena per corrida, luogo di esecuzioni dell\'Inquisizione e scenario di celebrazioni reali. A dicembre ospita il famoso mercatino di Natale madrileno.'],
      ],
    ],
    [
      'title'       => 'Mercado de San Miguel',
      'order'       => 4,
      'location'    => ['lat' => 40.4151, 'lng' => -3.7087],
      'description' => 'Just outside the northwest corner of Plaza Mayor, you\'ll find the Mercado de San Miguel, Madrid\'s most celebrated gourmet food market and a temple to Spanish gastronomy. Housed in a stunning early 20th-century cast-iron structure dating from 1916, the market was faithfully restored in 2009 and transformed into a vibrant food hall with over 30 stalls offering the finest produce from across Spain. This is the perfect mid-tour stop to taste vermouth poured from the barrel alongside anchovy-topped pintxos, sample freshly shucked Galician oysters, try artisan cheeses from Castile, or enjoy a glass of cava with jamón ibérico. Unlike many tourist markets, San Miguel strikes a good balance between quality and authenticity — many locals come here for their weekly shopping and to meet friends for a mid-morning aperitivo. The market is at its liveliest between 11am and 2pm on weekdays and throughout the day on weekends. Arrive hungry — resisting the temptation to try a little of everything is nearly impossible. Budget around €10–15 per person for a satisfying tasting experience.',
      'translations' => [
        'es' => ['title' => 'Mercado de San Miguel', 'description' => 'A la salida noroeste de la Plaza Mayor encontrará el Mercado de San Miguel, el mercado gastronómico más célebre de Madrid. Alojado en una impresionante estructura de hierro forjado de 1916 restaurada en 2009, ofrece más de 30 puestos con los mejores productos de toda España. Es la parada perfecta para degustar vermú de barril con pintxos, ostras gallegas, quesos artesanos castellanos o una copa de cava con jamón ibérico. El mercado está más animado entre las 11h y las 14h entre semana. Llegue con hambre — resistirse a probarlo todo es prácticamente imposible. Presupueste unos 10-15€ por persona.'],
        'fr' => ['title' => 'Le Mercado de San Miguel', 'description' => 'Juste à la sortie nord-ouest de la Plaza Mayor se trouve le Mercado de San Miguel, le marché gastronomique le plus célèbre de Madrid. Installé dans une superbe structure de fer forgé de 1916 restaurée en 2009, il propose plus de 30 stands offrant les meilleurs produits de toute l\'Espagne. C\'est l\'arrêt idéal pour déguster du vermouth au tonneau avec des pintxos, des huîtres de Galice, des fromages artisanaux de Castille ou un verre de cava avec du jamón ibérico. Arrivez affamé — résister à la tentation de tout goûter est pratiquement impossible.'],
        'de' => ['title' => 'Mercado de San Miguel', 'description' => 'Gleich außerhalb der nordwestlichen Ecke der Plaza Mayor finden Sie den Mercado de San Miguel, Madrids berühmtesten Gourmet-Markt. In einer beeindruckenden Gusseisen-Struktur von 1916, 2009 restauriert, bieten über 30 Stände die besten Produkte aus ganz Spanien. Hier können Sie Wermut vom Fass mit Pintxos, galicische Austern, kastilische Käsespezialitäten oder Cava mit Jamón Ibérico probieren. Kommen Sie hungrig — der Versuchung zu widerstehen, alles zu probieren, ist nahezu unmöglich. Rechnen Sie mit etwa 10-15€ pro Person.'],
        'it' => ['title' => 'Mercado de San Miguel', 'description' => 'Appena fuori dall\'angolo nord-ovest della Plaza Mayor troverete il Mercado de San Miguel, il mercato gastronomico più celebre di Madrid. Ospitato in una splendida struttura in ferro battuto del 1916 restaurata nel 2009, offre oltre 30 banchi con i migliori prodotti di tutta la Spagna. È la sosta perfetta per assaggiare vermouth alla spina con pintxos, ostriche galiziane, formaggi artigianali castigliani o un calice di cava con jamón ibérico. Arrivate affamati — resistere alla tentazione di assaggiare tutto è praticamente impossibile.'],
      ],
    ],
    [
      'title'       => 'Museo Nacional del Prado',
      'order'       => 5,
      'location'    => ['lat' => 40.4138, 'lng' => -3.6921],
      'description' => 'Your tour concludes at the Museo Nacional del Prado, one of the greatest art museums in the world and Spain\'s most visited cultural institution. Founded in 1819, the Prado houses a collection of over 20,000 works of art, of which approximately 1,800 are on permanent display across its neoclassical galleries. The museum\'s collection is unrivalled in its depth of Spanish, Flemish, and Italian painting from the 12th to early 20th centuries. The highlights are simply staggering: Velázquez\'s Las Meninas — arguably the most analysed painting in Western art history — hangs in Room 12 and rarely fails to stop visitors in their tracks. Nearby you\'ll find his extraordinary series of royal portraits and mythological scenes. Goya\'s Black Paintings, created directly onto the walls of his home in a period of profound personal darkness, are displayed in Rooms 65-67 and represent some of the most psychologically intense works ever made. El Greco\'s elongated, spiritual figures fill several rooms, while Bosch\'s triptych The Garden of Earthly Delights in Room 56A is one of the most discussed and debated paintings in history. Allow a minimum of two hours — serious art lovers could easily spend an entire day. The museum shop on the ground floor is excellent for art books and quality reproductions.',
      'translations' => [
        'es' => ['title' => 'Museo Nacional del Prado', 'description' => 'El tour concluye en el Museo Nacional del Prado, uno de los mayores museos de arte del mundo y la institución cultural más visitada de España. Fundado en 1819, alberga más de 20.000 obras de arte. Las Meninas de Velázquez — posiblemente el cuadro más analizado de la historia del arte occidental — cuelga en la Sala 12. Las Pinturas Negras de Goya, creadas directamente sobre las paredes de su casa durante un período de profunda oscuridad personal, son de las obras más psicológicamente intensas jamás realizadas. El tríptico El Jardín de las Delicias de El Bosco en la Sala 56A es uno de los cuadros más debatidos de la historia. Reserve un mínimo de dos horas para la visita.'],
        'fr' => ['title' => 'Le Museo Nacional del Prado', 'description' => 'Le tour s\'achève au Museo Nacional del Prado, l\'un des plus grands musées d\'art au monde et l\'institution culturelle la plus visitée d\'Espagne. Fondé en 1819, il abrite plus de 20 000 œuvres d\'art. Les Ménines de Velázquez — sans doute le tableau le plus analysé de l\'histoire de l\'art occidental — est exposé dans la Salle 12. Les Peintures noires de Goya, peintes directement sur les murs de sa maison durant une période de profonde obscurité personnelle, comptent parmi les œuvres les plus psychologiquement intenses jamais réalisées. Le triptyque Le Jardin des délices de Bosch est l\'un des tableaux les plus débattus de l\'histoire. Prévoyez un minimum de deux heures.'],
        'de' => ['title' => 'Museo Nacional del Prado', 'description' => 'Ihre Tour endet im Museo Nacional del Prado, einem der größten Kunstmuseen der Welt und Spaniens meistbesuchter Kulturinstitution. 1819 gegründet, beherbergt es über 20.000 Kunstwerke. Velázquez\' Las Meninas — wohl das meistanalysierte Gemälde der westlichen Kunstgeschichte — hängt in Saal 12. Goyas Schwarze Gemälde, direkt auf die Wände seines Hauses in einer Zeit tiefer persönlicher Finsternis gemalt, gehören zu den psychologisch intensivsten Werken überhaupt. Boschs Triptychon Der Garten der Lüste in Saal 56A ist eines der meistdiskutierten Gemälde der Geschichte. Planen Sie mindestens zwei Stunden ein.'],
        'it' => ['title' => 'Museo Nacional del Prado', 'description' => 'Il tour si conclude al Museo Nacional del Prado, uno dei più grandi musei d\'arte al mondo e l\'istituzione culturale più visitata della Spagna. Fondato nel 1819, ospita oltre 20.000 opere d\'arte. Las Meninas di Velázquez — probabilmente il dipinto più analizzato nella storia dell\'arte occidentale — è esposto nella Sala 12. Le Pitture Nere di Goya, realizzate direttamente sulle pareti della sua casa in un periodo di profonda oscurità personale, sono tra le opere psicologicamente più intense mai create. Il trittico Il Giardino delle Delizie di Bosch nella Sala 56A è uno dei dipinti più discussi della storia. Prevedete un minimo di due ore.'],
      ],
    ],
  ],
];

// ============================================================
// TOUR — BARCELONA: Gaudí's Barcelona — Modernisme & Mediterranean Magic
// ============================================================
$tours[] = [
  'title'       => 'Gaudí\'s Barcelona: Modernisme and Mediterranean Magic',
  'description' => 'Immerse yourself in the extraordinary architectural vision of Antoni Gaudí on this carefully curated tour through Barcelona\'s most iconic modernist landmarks. From the awe-inspiring spires of the Sagrada Família to the dreamlike terraces of Casa Batlló on the elegant Passeig de Gràcia, this tour reveals why Barcelona is considered one of the world\'s great architectural cities. Beyond Gaudí, the route takes you through the charming streets of the Gothic Quarter, past medieval churches and Roman ruins, and along the vibrant La Rambla to the historic waterfront. A tour that seamlessly blends art, architecture, history, and the irresistible energy of Mediterranean city life.',
  'duration'    => 210,
  'country'     => 'Spain',
  'city'        => 'Barcelona',
  'location'    => ['lat' => 41.3851, 'lng' => 2.1734],
  'translations' => [
    'es' => [
      'title'       => 'La Barcelona de Gaudí: Modernismo y magia mediterránea',
      'description' => 'Sumérjase en la extraordinaria visión arquitectónica de Antoni Gaudí en este tour por los hitos modernistas más icónicos de Barcelona. Desde las sobrecogedoras torres de la Sagrada Família hasta las terrazas oníricas de la Casa Batlló en el elegante Passeig de Gràcia, este recorrido revela por qué Barcelona es considerada una de las grandes ciudades arquitectónicas del mundo. Más allá de Gaudí, la ruta le lleva por el encantador Barrio Gótico, La Rambla y el paseo marítimo histórico. Arte, arquitectura, historia y la energía irresistible de la vida mediterránea.',
    ],
    'fr' => [
      'title'       => 'La Barcelone de Gaudí : Modernisme et magie méditerranéenne',
      'description' => 'Plongez dans la vision architecturale extraordinaire d\'Antoni Gaudí lors de ce tour à travers les monuments modernistes les plus emblématiques de Barcelone. Des flèches époustouflantes de la Sagrada Família aux terrasses oniriques de la Casa Batlló sur l\'élégant Passeig de Gràcia, ce parcours révèle pourquoi Barcelone est considérée comme l\'une des grandes villes architecturales du monde. Au-delà de Gaudí, l\'itinéraire traverse le Quartier Gothique, La Rambla et le front de mer historique.',
    ],
    'de' => [
      'title'       => 'Gaudís Barcelona: Modernisme und mediterrane Magie',
      'description' => 'Tauchen Sie ein in die außergewöhnliche architektonische Vision von Antoni Gaudí auf dieser Tour durch Barcelonas ikonischste modernistische Wahrzeichen. Von den atemberaubenden Türmen der Sagrada Família bis zu den traumhaften Terrassen der Casa Batlló am eleganten Passeig de Gràcia zeigt diese Tour, warum Barcelona als eine der großen Architekturstädte der Welt gilt. Die Route führt auch durch das bezaubernde Gotische Viertel, entlang der Rambla und zur historischen Uferpromenade.',
    ],
    'it' => [
      'title'       => 'La Barcellona di Gaudí: Modernismo e magia mediterranea',
      'description' => 'Immergetevi nella straordinaria visione architettonica di Antoni Gaudí in questo tour attraverso i monumenti modernisti più iconici di Barcellona. Dalle guglie mozzafiato della Sagrada Família alle terrazze oniriche della Casa Batlló sull\'elegante Passeig de Gràcia, questo percorso rivela perché Barcellona è considerata una delle grandi città architettoniche del mondo. Oltre Gaudí, l\'itinerario attraversa il Barrio Gótico, La Rambla e il lungomare storico.',
    ],
  ],
  'steps' => [
    [
      'title'       => 'Sagrada Família — Gaudí\'s Unfinished Masterpiece',
      'order'       => 1,
      'location'    => ['lat' => 41.4036, 'lng' => 2.1744],
      'description' => 'No visit to Barcelona is complete without standing before the Basílica de la Sagrada Família, Antoni Gaudí\'s extraordinary and still unfinished basilica that has been under continuous construction since 1882. Gaudí devoted the last 43 years of his life to this project, and when he died in 1926 — struck by a tram and initially unrecognised due to his humble appearance — less than a quarter of the church was complete. Construction continues today, funded entirely by entrance fees and private donations, with completion now targeted for around 2026, the centenary of Gaudí\'s death. The exterior is a revelation of organic forms inspired by nature: the Nativity Façade on the east side, the only part completed under Gaudí\'s direct supervision, bursts with naturalistic sculpture depicting the birth of Christ in extraordinary detail. The Passion Façade on the west side, designed by sculptor Josep Maria Subirachs, takes a starker, more angular approach that has divided opinion since its completion. Step inside and prepare to be overwhelmed: the interior forest of branching stone columns supports a ceiling of geometric vaults in gold, green, and blue that filters the light like a living canopy. The effect is unlike anything else in the world of architecture. Book tickets online well in advance — queues without pre-booking can exceed two hours.',
      'translations' => [
        'es' => ['title' => 'Sagrada Família — la obra maestra inacabada de Gaudí', 'description' => 'Ninguna visita a Barcelona está completa sin contemplar la Basílica de la Sagrada Família, la extraordinaria basílica inacabada de Gaudí en construcción continua desde 1882. Gaudí dedicó los últimos 43 años de su vida a este proyecto; cuando murió en 1926 — atropellado por un tranvía — menos de una cuarta parte estaba completada. La Fachada de la Natividad en el este, la única terminada bajo su supervisión directa, rebosa de escultura naturalista. En el interior, un bosque de columnas de piedra ramificada sostiene un techo de bóvedas geométricas en oro, verde y azul que filtra la luz como un dosel viviente. Reserve entradas con mucha antelación.'],
        'fr' => ['title' => 'La Sagrada Família — le chef-d\'œuvre inachevé de Gaudí', 'description' => 'Aucune visite de Barcelone n\'est complète sans se recueillir devant la Sagrada Família, l\'extraordinaire basilique inachevée de Gaudí en construction continue depuis 1882. Gaudí consacra les 43 dernières années de sa vie à ce projet ; il mourut en 1926, renversé par un tramway. La Façade de la Nativité, la seule achevée sous sa supervision directe, regorge de sculptures naturalistes. L\'intérieur est une forêt de colonnes de pierre ramifiées soutenant un plafond de voûtes géométriques en or, vert et bleu filtrant la lumière comme un auvent vivant. Réservez vos billets bien à l\'avance.'],
        'de' => ['title' => 'Sagrada Família — Gaudís unvollendetes Meisterwerk', 'description' => 'Kein Barcelona-Besuch ist vollständig ohne die Sagrada Família, Gaudís außergewöhnliche und noch immer unvollendete Basilika, an der seit 1882 gebaut wird. Gaudí widmete die letzten 43 Jahre seines Lebens diesem Projekt; als er 1926 starb — von einer Straßenbahn erfasst — war weniger als ein Viertel fertig. Die Geburtsfassade im Osten, der einzige unter seiner Aufsicht fertiggestellte Teil, strotzt vor naturalistischer Skulptur. Im Inneren tragen verzweigte Steinsäulen ein Deckengewölbe in Gold, Grün und Blau, das Licht wie ein lebendiges Blätterdach filtert. Buchen Sie Tickets weit im Voraus.'],
        'it' => ['title' => 'Sagrada Família — il capolavoro incompiuto di Gaudí', 'description' => 'Nessuna visita a Barcellona è completa senza ammirare la Sagrada Família, la straordinaria basilica incompiuta di Gaudí in costruzione continua dal 1882. Gaudí dedicò gli ultimi 43 anni della sua vita a questo progetto; morì nel 1926, investito da un tram. La Facciata della Natività a est, l\'unica completata sotto la sua supervisione diretta, è ricca di scultura naturalistica. All\'interno, una foresta di colonne di pietra ramificate sostiene un soffitto di volte geometriche in oro, verde e blu che filtra la luce come un baldacchino vivente. Prenotate i biglietti con largo anticipo.'],
      ],
    ],
    [
      'title'       => 'Passeig de Gràcia — Barcelona\'s Grand Boulevard',
      'order'       => 2,
      'location'    => ['lat' => 41.3924, 'lng' => 2.1649],
      'description' => 'From the Sagrada Família, walk southwest along the elegant Passeig de Gràcia, Barcelona\'s most prestigious avenue and an open-air museum of Catalan Modernisme architecture. Laid out in 1860 as part of Ildefons Cerdà\'s revolutionary Eixample urban expansion plan — with its distinctive chamfered street corners and octagonal city blocks — the boulevard quickly became the preferred address for Barcelona\'s wealthy bourgeoisie competing to commission the most impressive buildings. The result is an extraordinary concentration of architectural ambition. The so-called Manzana de la Discordia (Block of Discord) at numbers 35-43 contains three masterpieces by rival architects built within a decade of each other: Domènech i Montaner\'s Casa Lleó Morera (1906) at number 35, Puig i Cadafalch\'s Casa Amatller (1900) at number 41, and Gaudí\'s Casa Batlló (1906) at number 43. Each building represents a completely different interpretation of Modernisme, making this single block one of the most architecturally diverse in the world. The hexagonal pavement tiles, designed by Gaudí himself, were originally created specifically for the Passeig de Gràcia and have since become one of Barcelona\'s most recognised design icons.',
      'translations' => [
        'es' => ['title' => 'Passeig de Gràcia — el gran bulevar de Barcelona', 'description' => 'Camine hacia el suroeste por el elegante Passeig de Gràcia, la avenida más prestigiosa de Barcelona y un museo al aire libre de arquitectura modernista catalana. La llamada Manzana de la Discordia (números 35-43) contiene tres obras maestras de arquitectos rivales construidas en menos de una década: la Casa Lleó Morera de Domènech i Montaner, la Casa Amatller de Puig i Cadafalch y la Casa Batlló de Gaudí. Cada edificio representa una interpretación completamente distinta del Modernismo. Las baldosas hexagonales del pavimento, diseñadas por el propio Gaudí, se han convertido en uno de los iconos de diseño más reconocidos de Barcelona.'],
        'fr' => ['title' => 'Le Passeig de Gràcia — le grand boulevard de Barcelone', 'description' => 'Marchez vers le sud-ouest le long de l\'élégant Passeig de Gràcia, l\'avenue la plus prestigieuse de Barcelone et un musée en plein air d\'architecture moderniste catalane. Le Manzana de la Discordia (numéros 35-43) contient trois chefs-d\'œuvre d\'architectes rivaux : la Casa Lleó Morera de Domènech i Montaner, la Casa Amatller de Puig i Cadafalch et la Casa Batlló de Gaudí. Chaque édifice représente une interprétation radicalement différente du Modernisme. Les carreaux hexagonaux du trottoir, conçus par Gaudí lui-même, sont devenus l\'une des icônes les plus reconnues de Barcelone.'],
        'de' => ['title' => 'Passeig de Gràcia — Barcelonas große Prachtstraße', 'description' => 'Spazieren Sie südwestlich den eleganten Passeig de Gràcia entlang, Barcelonas prestigeträchtigste Allee und ein Freiluftmuseum katalanischer Modernisme-Architektur. Die Manzana de la Discordia (Nummern 35-43) enthält drei Meisterwerke rivalisierender Architekten: Domènech i Montaners Casa Lleó Morera, Puig i Cadafalchs Casa Amatller und Gaudís Casa Batlló. Jedes Gebäude repräsentiert eine völlig unterschiedliche Interpretation des Modernisme. Die sechseckigen Gehwegfliesen, von Gaudí selbst entworfen, sind zu einer der bekanntesten Design-Ikonen Barcelonas geworden.'],
        'it' => ['title' => 'Passeig de Gràcia — il grande viale di Barcellona', 'description' => 'Camminate verso sud-ovest lungo l\'elegante Passeig de Gràcia, il viale più prestigioso di Barcellona e un museo a cielo aperto di architettura modernista catalana. La cosiddetta Manzana de la Discordia (numeri 35-43) contiene tre capolavori di architetti rivali: la Casa Lleó Morera di Domènech i Montaner, la Casa Amatller di Puig i Cadafalch e la Casa Batlló di Gaudí. Ogni edificio rappresenta un\'interpretazione completamente diversa del Modernismo. Le piastrelle esagonali del marciapiede, disegnate dallo stesso Gaudí, sono diventate una delle icone di design più riconosciute di Barcellona.'],
      ],
    ],
    [
      'title'       => 'Casa Batlló — The House of Bones',
      'order'       => 3,
      'location'    => ['lat' => 41.3916, 'lng' => 2.1650],
      'description' => 'Casa Batlló at number 43 Passeig de Gràcia is widely considered one of Gaudí\'s greatest achievements and one of the most remarkable buildings ever constructed. Commissioned by industrialist Josep Batlló i Casanovas in 1904 and completed in 1906, the building is a total redesign of an existing structure, transformed by Gaudí into something that appears to have grown organically rather than been built. The façade is covered in a shimmering mosaic of broken ceramic tiles — trencadís — in blue, green, and turquoise that changes colour depending on the angle of the light and time of day. The skeletal balconies that give the building its nickname "Casa dels Ossos" (House of Bones) are said to represent human skulls and bones, though Gaudí himself spoke of the sea and the legend of Saint George and the dragon: the scaly roof representing the dragon\'s back, the tower topped with a cross representing the saint\'s lance. The interior is equally breathtaking: the light well at the centre of the building is lined in tiles that graduate from deep cobalt at the top to pale sky blue at the bottom, ensuring even lighting throughout the building at all times of day. The Magic Nights events on the rooftop terrace in summer are an unforgettable experience — book well ahead.',
      'translations' => [
        'es' => ['title' => 'Casa Batlló — la casa de los huesos', 'description' => 'La Casa Batlló en el número 43 del Passeig de Gràcia es considerada una de las mayores obras de Gaudí y uno de los edificios más extraordinarios jamás construidos. La fachada está cubierta de un mosaico centelleante de baldosas cerámicas rotas — trencadís — en azul, verde y turquesa que cambia de color según el ángulo de la luz. Los balcones esqueléticos que le dan el apodo de "Casa dels Ossos" se dice que representan calaveras y huesos, aunque Gaudí hablaba del mar y la leyenda de Sant Jordi y el dragón: el tejado escamoso como el lomo del dragón, la torre rematada con una cruz como la lanza del santo. El patio interior está forrado de azulejos que gradúan del cobalto oscuro arriba al azul cielo claro abajo.'],
        'fr' => ['title' => 'La Casa Batlló — la maison des os', 'description' => 'La Casa Batlló au 43 Passeig de Gràcia est considérée comme l\'une des plus grandes réalisations de Gaudí. La façade est couverte d\'une mosaïque chatoyante de carreaux de céramique brisés — trencadís — en bleu, vert et turquoise qui change de couleur selon l\'angle de la lumière. Les balcons squelettiques qui lui valent le surnom de « Maison des Os » représenteraient des crânes et des os, bien que Gaudí parlât de la mer et de la légende de Saint Georges et du dragon : le toit écailleux comme le dos du dragon, la tour surmontée d\'une croix comme la lance du saint. Le puits de lumière intérieur est tapissé de carreaux dégradés du cobalt foncé en haut au bleu ciel en bas.'],
        'de' => ['title' => 'Casa Batlló — das Knochenhaus', 'description' => 'Die Casa Batlló an der Nummer 43 des Passeig de Gràcia gilt als eines von Gaudís größten Meisterwerken. Die Fassade ist mit einem schimmernden Mosaik aus gebrochenen Keramikfliesen — Trencadís — in Blau, Grün und Türkis bedeckt, das je nach Lichteinfall die Farbe wechselt. Die skelettartigen Balkone, die dem Gebäude den Spitznamen „Knochenhaus" geben, sollen Schädel und Knochen darstellen, doch Gaudí sprach vom Meer und der Legende des Heiligen Georg und des Drachen: das schuppige Dach als Drachenrücken, der Turm mit Kreuz als Lanze des Heiligen. Der innere Lichthof ist mit Fliesen ausgekleidet, die von tiefem Kobalt oben bis hellem Himmelblau unten graduieren.'],
        'it' => ['title' => 'Casa Batlló — la casa delle ossa', 'description' => 'La Casa Batlló al numero 43 del Passeig de Gràcia è ampiamente considerata uno dei capolavori di Gaudí. La facciata è coperta da un mosaico scintillante di piastrelle di ceramica rotte — trencadís — in blu, verde e turchese che cambia colore a seconda dell\'angolo della luce. I balconi scheletrici che danno all\'edificio il soprannome di "Casa delle Ossa" rappresenterebbero teschi e ossa, sebbene Gaudí parlasse del mare e della leggenda di San Giorgio e il drago: il tetto squamoso come il dorso del drago, la torre sormontata da una croce come la lancia del santo. Il pozzo di luce interno è rivestito di piastrelle che sfumano dal cobalto scuro in alto all\'azzurro cielo in basso.'],
      ],
    ],
    [
      'title'       => 'Barri Gòtic — The Gothic Quarter',
      'order'       => 4,
      'location'    => ['lat' => 41.3833, 'lng' => 2.1762],
      'description' => 'Leave the modernist grandeur of the Eixample behind and step back 2,000 years into the Barri Gòtic, Barcelona\'s ancient Gothic Quarter and the historic heart of the city. Built on and around the original Roman settlement of Barcino, founded in the 1st century BC, the quarter is a labyrinth of narrow medieval streets, atmospheric plazas, and remarkable historic monuments compressed into a remarkably small area. Begin at the Plaça de Sant Jaume, the political heart of Catalonia, where the Palau de la Generalitat (seat of the Catalan government) and the Ajuntament (City Hall) face each other across the square — both buildings incorporate medieval fabric within their later Renaissance and Baroque exteriors. Head north along Carrer del Bisbe to find the Bridge of Sighs, a neo-Gothic bridge that connects two parts of the Palau de la Generalitat and is one of the most photographed spots in Barcelona. Continue to the magnificent Barcelona Cathedral, construction of which began in 1298 on the site of a Romanesque church. The cathedral\'s cloisters are home to 13 white geese — one for each year of Saint Eulalia\'s life — a tradition maintained for centuries. In the basement of the nearby Museu d\'Història de Barcelona, you can walk above an extraordinarily well-preserved Roman archaeological site covering several city blocks.',
      'translations' => [
        'es' => ['title' => 'Barri Gòtic — el Barrio Gótico', 'description' => 'Deje atrás el modernismo del Eixample y retroceda 2.000 años al Barri Gòtic, el Barrio Gótico de Barcelona y corazón histórico de la ciudad. Construido sobre el asentamiento romano de Barcino del siglo I a.C., es un laberinto de estrechas calles medievales, plazas atmosféricas y monumentos históricos. Comience en la Plaça de Sant Jaume, corazón político de Cataluña. Recorra el Carrer del Bisbe para encontrar el Puente de los Suspiros, uno de los puntos más fotografiados de Barcelona. Los claustros de la Catedral albergan 13 gansos blancos, uno por cada año de vida de Santa Eulalia. En el subsuelo del Museu d\'Història puede caminar sobre una extraordinaria ciudad romana conservada.'],
        'fr' => ['title' => 'Le Barri Gòtic — le Quartier Gothique', 'description' => 'Laissez derrière vous le modernisme de l\'Eixample et remontez 2 000 ans dans le Barri Gòtic, le cœur historique de Barcelone. Construit sur l\'ancien établissement romain de Barcino du Ier siècle av. J.-C., c\'est un labyrinthe de ruelles médiévales, de places atmosphériques et de monuments historiques. Commencez par la Plaça de Sant Jaume, cœur politique de la Catalogne. Parcourez le Carrer del Bisbe pour trouver le Pont des Soupirs, l\'un des lieux les plus photographiés de Barcelone. Les cloîtres de la Cathédrale abritent 13 oies blanches en mémoire de Sainte Eulalie.'],
        'de' => ['title' => 'Barri Gòtic — das Gotische Viertel', 'description' => 'Lassen Sie die modernistische Pracht des Eixample hinter sich und reisen Sie 2.000 Jahre zurück ins Barri Gòtic, das historische Herz Barcelonas. Erbaut auf der römischen Siedlung Barcino aus dem 1. Jahrhundert v. Chr., ist es ein Labyrinth enger mittelalterlicher Gassen, stimmungsvoller Plätze und bemerkenswerter historischer Monumente. Beginnen Sie an der Plaça de Sant Jaume, dem politischen Herzen Kataloniens. Am Carrer del Bisbe finden Sie die Seufzerbrücke, einen der meistfotografierten Orte Barcelonas. Die Kreuzgänge der Kathedrale beherbergen 13 weiße Gänse zum Gedenken an die Heilige Eulalia.'],
        'it' => ['title' => 'Barri Gòtic — il Quartiere Gotico', 'description' => 'Lasciatevi alle spalle il modernismo dell\'Eixample e tornate indietro di 2.000 anni nel Barri Gòtic, il cuore storico di Barcellona. Costruito sull\'antico insediamento romano di Barcino del I secolo a.C., è un labirinto di strette vie medievali, piazze suggestive e monumenti storici. Iniziate dalla Plaça de Sant Jaume, cuore politico della Catalogna. Percorrete il Carrer del Bisbe per trovare il Ponte dei Sospiri, uno dei luoghi più fotografati di Barcellona. I chiostri della Cattedrale ospitano 13 oche bianche in memoria di Santa Eulalia.'],
      ],
    ],
    [
      'title'       => 'La Barceloneta — The Mediterranean Waterfront',
      'order'       => 5,
      'location'    => ['lat' => 41.3809, 'lng' => 2.1897],
      'description' => 'Complete your Barcelona experience at La Barceloneta, the city\'s beloved beach neighbourhood and its connection to the Mediterranean Sea. This distinctive triangular district, built on reclaimed land in the 18th century to rehouse fishermen displaced by the construction of the Ciutadella fortress, retains much of its original working-class character despite being completely surrounded by tourism. The narrow parallel streets — unusually tight even by Barcelona standards, the result of a deliberate urban planning strategy to maximise shade in the summer heat — are lined with traditional seafood restaurants serving fresh paella, fideuà, and grilled fish straight from the Barceloneta fish market. Head to the beach itself — nearly 4 kilometres of golden sand backed by a palm-lined promenade — and walk north to the Olympic Port, built for the 1992 Barcelona Olympics that transformed the city\'s relationship with its coastline. Frank Gehry\'s enormous copper Fish sculpture catches the late afternoon light magnificently near the Port. For the best views of the city skyline from the sea, take the cable car from the Torre de Sant Sebastià up to Montjuïc — the views are spectacular and the ride itself is a memorable experience. End with a cold Estrella Damm and a plate of fresh anchovies at one of the chiringuitos on the beach as the sun sets over the city.',
      'translations' => [
        'es' => ['title' => 'La Barceloneta — el paseo marítimo mediterráneo', 'description' => 'Complete su experiencia barcelonesa en La Barceloneta, el querido barrio playero de la ciudad y su conexión con el Mediterráneo. Este distrito triangular, construido sobre terrenos ganados al mar en el siglo XVIII, conserva su carácter obrero original. Las estrechas calles paralelas están flanqueadas por restaurantes de marisco que sirven paella, fideuà y pescado fresco. Pasee por la playa — casi 4 kilómetros de arena dorada — hasta el Puerto Olímpico, construido para las Olimpiadas de 1992. Tome el teleférico de la Torre de Sant Sebastià a Montjuïc para las mejores vistas. Termine con una Estrella Damm fría y un plato de boquerones en un chiringuito al atardecer.'],
        'fr' => ['title' => 'La Barceloneta — le front de mer méditerranéen', 'description' => 'Complétez votre expérience barcelonaise à La Barceloneta, le quartier balnéaire bien-aimé de la ville. Ce quartier triangulaire, construit sur des terres gagnées sur la mer au XVIIIe siècle, conserve son caractère populaire d\'origine. Les ruelles parallèles étroites sont bordées de restaurants de fruits de mer servant paella, fideuà et poisson frais. Promenez-vous sur la plage — près de 4 kilomètres de sable doré — jusqu\'au Port Olympique, construit pour les JO de 1992. Prenez le téléphérique de la Torre de Sant Sebastià jusqu\'à Montjuïc pour les plus belles vues. Terminez avec une Estrella Damm fraîche au coucher du soleil.'],
        'de' => ['title' => 'La Barceloneta — die mediterrane Uferpromenade', 'description' => 'Vervollständigen Sie Ihr Barcelona-Erlebnis in La Barceloneta, dem beliebten Strandviertel der Stadt. Dieses dreieckige Viertel, im 18. Jahrhundert auf aufgeschüttetem Land erbaut, bewahrt seinen ursprünglichen Arbeitercharakter. Die engen parallelen Gassen sind von Meeresfrüchte-Restaurants mit frischer Paella, Fideuà und Grillfisch gesäumt. Spazieren Sie am Strand entlang — fast 4 Kilometer goldener Sand — zum Olympischen Hafen von 1992. Nehmen Sie die Seilbahn von der Torre de Sant Sebastià nach Montjuïc für die besten Ausblicke. Enden Sie mit einem kühlen Estrella Damm bei Sonnenuntergang.'],
        'it' => ['title' => 'La Barceloneta — il lungomare mediterraneo', 'description' => 'Completate la vostra esperienza barcellonese alla Barceloneta, l\'amato quartiere balneare della città. Questo quartiere triangolare, costruito su terreni bonificati nel XVIII secolo, conserva il suo carattere popolare originario. Le strette vie parallele sono fiancheggiate da ristoranti di pesce con paella fresca, fideuà e pesce alla griglia. Passeggiate sulla spiaggia — quasi 4 chilometri di sabbia dorata — fino al Porto Olimpico del 1992. Prendete la funivia dalla Torre de Sant Sebastià a Montjuïc per le migliori viste. Concludete con una Estrella Damm fresca e un piatto di acciughe al tramonto.'],
      ],
    ],
  ],
];

// ============================================================
// TOUR — ROME: Eternal Rome — From the Colosseum to the Trevi Fountain
// ============================================================
$tours[] = [
  'title'       => 'Eternal Rome: From the Colosseum to the Trevi Fountain',
  'description' => 'Walk through three thousand years of history on this unforgettable tour of Rome\'s most celebrated landmarks. The Eternal City is unlike anywhere else on earth — a place where an ancient Roman temple stands next to a Renaissance church, where Baroque fountains erupt from medieval piazzas, and where the weight of history is felt on every street corner. This tour takes you from the mighty Colosseum and the Roman Forum — the political and civic heart of the ancient world — through the winding streets of the historic centre to the Vatican Museums, the Sistine Chapel, and the incomparable Trevi Fountain. Whether it\'s your first visit to Rome or your tenth, this city never fails to overwhelm and inspire.',
  'duration'    => 240,
  'country'     => 'Italy',
  'city'        => 'Rome',
  'location'    => ['lat' => 41.9028, 'lng' => 12.4964],
  'translations' => [
    'es' => [
      'title'       => 'Roma eterna: del Coliseo a la Fontana di Trevi',
      'description' => 'Recorra tres mil años de historia en este inolvidable tour por los monumentos más célebres de Roma. La Ciudad Eterna es un lugar donde un templo romano antiguo se alza junto a una iglesia renacentista, donde fuentes barrocas brotan de plazas medievales y el peso de la historia se siente en cada esquina. Este recorrido le lleva del majestuoso Coliseo y el Foro Romano hasta los Museos Vaticanos, la Capilla Sixtina y la incomparable Fontana di Trevi.',
    ],
    'fr' => [
      'title'       => 'Rome éternelle : du Colisée à la Fontaine de Trevi',
      'description' => 'Traversez trois mille ans d\'histoire lors de cette visite inoubliable des monuments les plus célèbres de Rome. La Ville Éternelle est un lieu où un temple romain antique côtoie une église Renaissance, où des fontaines baroques jaillissent de piazzas médiévales et où le poids de l\'histoire se ressent à chaque coin de rue. Ce parcours vous mène du majestueux Colisée et du Forum Romain aux Musées du Vatican, à la Chapelle Sixtine et à l\'incomparable Fontaine de Trevi.',
    ],
    'de' => [
      'title'       => 'Ewiges Rom: Vom Kolosseum zum Trevi-Brunnen',
      'description' => 'Wandern Sie durch dreitausend Jahre Geschichte auf dieser unvergesslichen Tour durch Roms berühmteste Wahrzeichen. Die Ewige Stadt ist ein Ort, wo ein antiker römischer Tempel neben einer Renaissance-Kirche steht, wo Barockbrunnen aus mittelalterlichen Piazzas emporspringen und wo das Gewicht der Geschichte an jeder Straßenecke spürbar ist. Diese Tour führt vom mächtigen Kolosseum und dem Forum Romanum zu den Vatikanischen Museen, der Sixtinischen Kapelle und dem unvergleichlichen Trevi-Brunnen.',
    ],
    'it' => [
      'title'       => 'Roma eterna: dal Colosseo alla Fontana di Trevi',
      'description' => 'Attraversate tremila anni di storia in questo tour indimenticabile dei monumenti più celebri di Roma. La Città Eterna è un luogo dove un tempio romano antico sorge accanto a una chiesa rinascimentale, dove fontane barocche erompono da piazze medievali e il peso della storia si avverte ad ogni angolo. Questo percorso vi porta dal maestoso Colosseo e dal Foro Romano ai Musei Vaticani, alla Cappella Sistina e all\'incomparabile Fontana di Trevi.',
    ],
  ],
  'steps' => [
    [
      'title'       => 'The Colosseum — Rome\'s Greatest Arena',
      'order'       => 1,
      'location'    => ['lat' => 41.8902, 'lng' => 12.4922],
      'description' => 'Begin your Roman journey at the Colosseum — the Flavian Amphitheatre — the largest ancient amphitheatre ever built and an enduring symbol of Imperial Rome\'s power, ambition, and brutality. Commissioned by Emperor Vespasian around 70 AD and completed under his son Titus in 80 AD, the Colosseum could hold between 50,000 and 80,000 spectators who came to watch gladiatorial combat, wild animal hunts (venationes), public executions, and dramatic re-enactments of famous battles. The engineering achievement is extraordinary even by modern standards: the elliptical structure is 188 metres long, 156 metres wide, and 48 metres tall, constructed using approximately 100,000 cubic metres of travertine marble — all transported from quarries near Tivoli — along with volcanic tuff, brick, and concrete. The complex system of underground tunnels and chambers (the hypogeum), only recently opened to visitors, housed the animals, gladiators, and mechanical elevators used to raise participants dramatically into the arena. The Colosseum was in continuous use for nearly 400 years before being converted into housing, workshops, a religious complex, and ultimately a quarry during the medieval period — which explains the missing sections of the outer wall. Today it remains one of the most visited monuments in the world, attracting over 7 million visitors annually. Book skip-the-line tickets online — the queues without pre-booking are formidable.',
      'translations' => [
        'es' => ['title' => 'El Coliseo — la mayor arena de Roma', 'description' => 'Comience su recorrido romano en el Coliseo — el Anfiteatro Flavio — el mayor anfiteatro antiguo jamás construido y símbolo perdurable del poder de la Roma Imperial. Encargado por el emperador Vespasiano alrededor del año 70 d.C. y completado bajo su hijo Tito en el 80 d.C., podía albergar entre 50.000 y 80.000 espectadores. La estructura elíptica mide 188 metros de largo, 156 de ancho y 48 de alto, construida con aproximadamente 100.000 metros cúbicos de mármol travertino. El complejo sistema de túneles subterráneos (el hipogeo), recientemente abierto al público, alojaba animales, gladiadores y elevadores mecánicos. Reserve entradas sin cola online.'],
        'fr' => ['title' => 'Le Colisée — la plus grande arène de Rome', 'description' => 'Commencez votre voyage romain au Colisée — l\'Amphithéâtre Flavien — le plus grand amphithéâtre antique jamais construit. Commandé par l\'empereur Vespasien vers 70 apr. J.-C. et achevé sous son fils Titus en 80 apr. J.-C., il pouvait accueillir entre 50 000 et 80 000 spectateurs. La structure elliptique mesure 188 mètres de long, 156 de large et 48 de haut, construite avec environ 100 000 mètres cubes de marbre travertin. Le système complexe de tunnels souterrains (l\'hypogée), récemment ouvert aux visiteurs, abritait animaux, gladiateurs et ascenseurs mécaniques. Réservez des billets coupe-file en ligne.'],
        'de' => ['title' => 'Das Kolosseum — Roms größte Arena', 'description' => 'Beginnen Sie Ihre römische Reise am Kolosseum — dem Flavischen Amphitheater — dem größten antiken Amphitheater, das je gebaut wurde. Um 70 n. Chr. von Kaiser Vespasian in Auftrag gegeben und unter seinem Sohn Titus 80 n. Chr. vollendet, fasste es zwischen 50.000 und 80.000 Zuschauer. Die elliptische Struktur ist 188 Meter lang, 156 Meter breit und 48 Meter hoch, aus rund 100.000 Kubikmetern Travertin erbaut. Das komplexe System unterirdischer Tunnel (das Hypogäum), erst kürzlich für Besucher geöffnet, beherbergte Tiere, Gladiatoren und mechanische Aufzüge. Buchen Sie Tickets ohne Warteschlange online.'],
        'it' => ['title' => 'Il Colosseo — la più grande arena di Roma', 'description' => 'Iniziate il vostro viaggio romano al Colosseo — l\'Anfiteatro Flavio — il più grande anfiteatro antico mai costruito. Commissionato dall\'imperatore Vespasiano intorno al 70 d.C. e completato sotto suo figlio Tito nell\'80 d.C., poteva ospitare tra 50.000 e 80.000 spettatori. La struttura ellittica misura 188 metri di lunghezza, 156 di larghezza e 48 di altezza, costruita con circa 100.000 metri cubi di travertino. Il complesso sistema di tunnel sotterranei (l\'ipogeo), recentemente aperto ai visitatori, ospitava animali, gladiatori e ascensori meccanici. Prenotate biglietti salta-fila online.'],
      ],
    ],
    [
      'title'       => 'Roman Forum & Palatine Hill',
      'order'       => 2,
      'location'    => ['lat' => 41.8925, 'lng' => 12.4853],
      'description' => 'Immediately adjacent to the Colosseum lies the Roman Forum — the Foro Romano — the beating heart of the ancient Roman world for over a thousand years. This sprawling archaeological site, now a romantic landscape of towering columns, triumphal arches, ruined temples, and basilicas, was once the centre of Roman public life: the place where elections were held, criminals tried, gladiators honoured, and emperors mourned. Walking through the Forum today requires some imagination to reconstruct its former glory, but the individual monuments are remarkable. The Temple of Saturn (497 BC), one of the oldest temples in Rome, still stands with eight of its grey granite columns intact. The Arch of Titus (81 AD), erected to commemorate the sack of Jerusalem, features interior reliefs showing Roman soldiers carrying the Menorah from the Temple — these images had a profound influence on later triumphal arch design throughout Europe. The Temple of Vesta, where the sacred flame of Rome was kept burning by the Vestal Virgins, is one of the most evocative ruins in the entire complex. From the Forum, climb the Palatine Hill — the most central of Rome\'s seven hills and, according to legend, the location of the city\'s founding by Romulus in 753 BC — for spectacular panoramic views over the Forum below and the Circus Maximus, ancient Rome\'s chariot-racing stadium, on the other side.',
      'translations' => [
        'es' => ['title' => 'Foro Romano y Monte Palatino', 'description' => 'Junto al Coliseo se extiende el Foro Romano, corazón palpitante del mundo romano antiguo durante más de mil años. El Templo de Saturno (497 a.C.) conserva ocho de sus columnas de granito gris. El Arco de Tito (81 d.C.), erigido para conmemorar el saqueo de Jerusalén, presenta relieves interiores con soldados romanos portando la Menorá del Templo. El Templo de Vesta, donde las Vestales mantenían encendida la llama sagrada de Roma, es una de las ruinas más evocadoras. Desde el Foro, suba al Monte Palatino — según la leyenda, el lugar de la fundación de Roma por Rómulo en 753 a.C. — para vistas panorámicas del Foro y el Circo Máximo.'],
        'fr' => ['title' => 'Le Forum Romain et le Mont Palatin', 'description' => 'Adjacent au Colisée s\'étend le Forum Romain, cœur battant du monde antique pendant plus de mille ans. Le Temple de Saturne (497 av. J.-C.) conserve huit de ses colonnes de granit gris. L\'Arc de Titus (81 apr. J.-C.), érigé pour commémorer le sac de Jérusalem, présente des reliefs montrant des soldats romains portant le Candélabre du Temple. Le Temple de Vesta, où les Vestales entretenaient la flamme sacrée de Rome, est l\'une des ruines les plus évocatrices. Montez au Mont Palatin — selon la légende, le lieu de fondation de Rome par Romulus en 753 av. J.-C. — pour des vues panoramiques spectaculaires.'],
        'de' => ['title' => 'Forum Romanum & Palatin-Hügel', 'description' => 'Unmittelbar neben dem Kolosseum liegt das Forum Romanum, das pulsierende Herz der antiken römischen Welt über tausend Jahre lang. Der Saturntempel (497 v. Chr.) steht noch mit acht seiner grauen Granitsäulen. Der Titusbogen (81 n. Chr.), errichtet zur Erinnerung an die Plünderung Jerusalems, zeigt Reliefs mit römischen Soldaten, die die Menora aus dem Tempel tragen. Der Vesta-Tempel, wo die Vestalinnen die heilige Flamme Roms am Brennen hielten, ist eine der eindrucksvollsten Ruinen. Besteigen Sie den Palatin — laut Legende der Gründungsort Roms durch Romulus 753 v. Chr. — für spektakuläre Panoramablicke.'],
        'it' => ['title' => 'Foro Romano e Colle Palatino', 'description' => 'Adiacente al Colosseo si estende il Foro Romano, cuore pulsante del mondo antico per oltre mille anni. Il Tempio di Saturno (497 a.C.) conserva otto delle sue colonne di granito grigio. L\'Arco di Tito (81 d.C.), eretto per commemorare il sacco di Gerusalemme, presenta rilievi con soldati romani che portano la Menorah dal Tempio. Il Tempio di Vesta, dove le Vestali mantenevano accesa la fiamma sacra di Roma, è una delle rovine più evocative. Salite al Colle Palatino — secondo la leggenda, il luogo della fondazione di Roma da parte di Romolo nel 753 a.C. — per viste panoramiche spettacolari.'],
      ],
    ],
    [
      'title'       => 'Pantheon — Temple of the Gods',
      'order'       => 3,
      'location'    => ['lat' => 41.8986, 'lng' => 12.4769],
      'description' => 'A twenty-minute walk northwest from the Forum brings you to one of the best-preserved buildings from antiquity and arguably the most influential building in Western architectural history: the Pantheon. Built as a temple to all the gods of ancient Rome, the current structure was commissioned by Emperor Hadrian around 125 AD to replace an earlier temple built by Marcus Agrippa — whose name, confusingly, still appears on the inscription above the entrance porch. The Pantheon\'s survival over nearly 2,000 years is largely due to its conversion into a Christian church in 609 AD, which saved it from the quarrying that destroyed so many other Roman monuments. The building\'s engineering genius is concentrated in its extraordinary dome: at 43.3 metres in diameter, it remained the world\'s largest dome for over 1,300 years until Brunelleschi completed the Florence Cathedral dome in 1436. The dome is a perfect hemisphere — if extended downward, it would exactly touch the floor — and at its apex is the oculus, an open circular hole 8.8 metres in diameter that is the building\'s only source of natural light. The oculus is open to the sky: on rainy days, a slight slope in the floor and concealed drainage channels remove the water that falls in. The tombs of Renaissance painter Raphael and King Victor Emmanuel II of unified Italy are among several notable burials within. Entrance is now ticketed following years of free admission.',
      'translations' => [
        'es' => ['title' => 'El Panteón — templo de los dioses', 'description' => 'A veinte minutos a pie del Foro se encuentra el Panteón, uno de los edificios antiguos mejor conservados del mundo y posiblemente el más influyente de la historia de la arquitectura occidental. Construido por el Emperador Adriano alrededor del año 125 d.C., su cúpula de 43,3 metros de diámetro fue la más grande del mundo durante más de 1.300 años. La cúpula es un hemisferio perfecto; en su cúspide se abre el óculo, un agujero circular de 8,8 metros de diámetro que es la única fuente de luz natural. El óculo está abierto al cielo: los días de lluvia, una ligera pendiente en el suelo y canales de drenaje ocultos evacuaban el agua. Alberga las tumbas de Rafael y del Rey Víctor Manuel II.'],
        'fr' => ['title' => 'Le Panthéon — temple des dieux', 'description' => 'À vingt minutes à pied du Forum se trouve le Panthéon, l\'un des bâtiments antiques les mieux conservés et sans doute le plus influent de l\'histoire de l\'architecture occidentale. Construit par l\'Empereur Hadrien vers 125 apr. J.-C., son dôme de 43,3 mètres de diamètre est resté le plus grand au monde pendant plus de 1 300 ans. Le dôme est un hémisphère parfait ; à son sommet s\'ouvre l\'oculus, un trou circulaire de 8,8 mètres de diamètre, seule source de lumière naturelle. L\'oculus est ouvert au ciel : les jours de pluie, une légère pente du sol évacue l\'eau. Il abrite les tombeaux de Raphaël et du Roi Victor-Emmanuel II.'],
        'de' => ['title' => 'Das Pantheon — Tempel der Götter', 'description' => 'Zwanzig Gehminuten nordwestlich vom Forum erreichen Sie das Pantheon, eines der besterhaltenen antiken Gebäude und wohl das einflussreichste in der Geschichte der westlichen Architektur. Um 125 n. Chr. von Kaiser Hadrian erbaut, blieb seine Kuppel mit 43,3 Metern Durchmesser über 1.300 Jahre die größte der Welt. Die Kuppel ist eine perfekte Halbkugel; an ihrem Scheitel öffnet sich der Okulus, ein kreisrundes Loch von 8,8 Metern Durchmesser als einzige natürliche Lichtquelle. Bei Regen leiten eine leichte Bodenneigung und verborgene Kanäle das Wasser ab. Hier befinden sich die Gräber von Raffael und König Viktor Emanuel II.'],
        'it' => ['title' => 'Il Pantheon — tempio degli dèi', 'description' => 'A venti minuti a piedi dal Foro si trova il Pantheon, uno degli edifici antichi meglio conservati e probabilmente il più influente nella storia dell\'architettura occidentale. Costruito dall\'Imperatore Adriano intorno al 125 d.C., la sua cupola di 43,3 metri di diametro rimase la più grande al mondo per oltre 1.300 anni. La cupola è un emisfero perfetto; al suo apice si apre l\'oculo, un foro circolare di 8,8 metri di diametro, unica fonte di luce naturale. L\'oculo è aperto al cielo: nei giorni di pioggia, una leggera pendenza del pavimento e canali nascosti evacuano l\'acqua. Ospita le tombe di Raffaello e del Re Vittorio Emanuele II.'],
      ],
    ],
    [
      'title'       => 'Vatican Museums & Sistine Chapel',
      'order'       => 4,
      'location'    => ['lat' => 41.9065, 'lng' => 12.4536],
      'description' => 'Cross the Tiber River to Vatican City — the world\'s smallest sovereign state at just 44 hectares — to visit the Vatican Museums, one of the largest and most important museum complexes in the world. Founded by Pope Julius II in the early 16th century, the museums contain the accumulated artistic treasures of the Catholic Church spanning nearly 2,000 years of history, displayed across 54 galleries and covering 7 kilometres of corridors if walked in their entirety. The journey through the museums is itself a remarkable experience: the Gallery of Maps features 40 topographical maps of Italy painted between 1580 and 1585 with extraordinary precision; the Gallery of Tapestries displays Flemish tapestries woven from Raphael\'s cartoons in the 1520s; and the Hall of the Candelabra is lined with ancient Roman sculpture of the highest quality. The inevitable and absolute highlight, however, is the Sistine Chapel. Painted by Michelangelo between 1508 and 1512 (the ceiling) and 1536 and 1541 (the Last Judgement on the altar wall), this is one of the supreme achievements in the history of Western art. The famous central panel depicting the Creation of Adam — in which God\'s finger almost touches the languid hand of the first man — is the most reproduced detail, but the ceiling as a whole is a staggering feat of physical endurance and artistic genius by a sculptor who had never previously worked in fresco on any significant scale. Photography without flash is permitted in the museums but not in the Sistine Chapel. Book tickets months in advance for July and August.',
      'translations' => [
        'es' => ['title' => 'Museos Vaticanos y Capilla Sixtina', 'description' => 'Cruce el Tíber hasta la Ciudad del Vaticano — el estado soberano más pequeño del mundo con sólo 44 hectáreas — para visitar los Museos Vaticanos, uno de los mayores complejos museísticos del mundo con 54 galerías y 7 kilómetros de pasillos. La Galería de los Mapas presenta 40 mapas topográficos de Italia pintados entre 1580 y 1585. El punto culminante indiscutible es la Capilla Sixtina, pintada por Miguel Ángel entre 1508 y 1512 (el techo) y 1536-1541 (el Juicio Final). El famoso panel central de la Creación de Adán es el detalle más reproducido, pero el techo en su conjunto es una hazaña sobrecogedora de genio artístico. Reserve entradas con meses de antelación en julio y agosto.'],
        'fr' => ['title' => 'Les Musées du Vatican et la Chapelle Sixtine', 'description' => 'Traversez le Tibre vers la Cité du Vatican — le plus petit État souverain du monde avec seulement 44 hectares — pour visiter les Musées du Vatican, l\'un des plus importants complexes muséaux au monde avec 54 galeries et 7 kilomètres de couloirs. La Galerie des Cartes présente 40 cartes topographiques de l\'Italie peintes entre 1580 et 1585. Le point culminant absolu est la Chapelle Sixtine, peinte par Michel-Ange entre 1508 et 1512 (le plafond) et 1536-1541 (le Jugement Dernier). Le célèbre panneau central de la Création d\'Adam est le détail le plus reproduit. Réservez des mois à l\'avance pour juillet et août.'],
        'de' => ['title' => 'Vatikanische Museen & Sixtinische Kapelle', 'description' => 'Überqueren Sie den Tiber zur Vatikanstadt — dem kleinsten souveränen Staat der Welt mit nur 44 Hektar — um die Vatikanischen Museen zu besuchen, einen der wichtigsten Museumskomplexe der Welt mit 54 Galerien und 7 Kilometer Korridoren. Die Galerie der Landkarten zeigt 40 topographische Karten Italiens, gemalt zwischen 1580 und 1585. Der absolute Höhepunkt ist die Sixtinische Kapelle, zwischen 1508 und 1512 (Decke) und 1536-1541 (Jüngstes Gericht) von Michelangelo gemalt. Das berühmte zentrale Bild der Erschaffung Adams ist das meistreproduzierte Detail. Buchen Sie Monate im Voraus für Juli und August.'],
        'it' => ['title' => 'Musei Vaticani e Cappella Sistina', 'description' => 'Attraversate il Tevere verso la Città del Vaticano — il più piccolo stato sovrano del mondo con soli 44 ettari — per visitare i Musei Vaticani, uno dei più importanti complessi museali del mondo con 54 gallerie e 7 chilometri di corridoi. La Galleria delle Carte Geografiche presenta 40 mappe topografiche dell\'Italia dipinte tra il 1580 e il 1585. Il culmine assoluto è la Cappella Sistina, dipinta da Michelangelo tra il 1508 e il 1512 (il soffitto) e il 1536-1541 (il Giudizio Universale). Il celebre pannello centrale della Creazione di Adamo è il dettaglio più riprodotto. Prenotate con mesi di anticipo per luglio e agosto.'],
      ],
    ],
    [
      'title'       => 'Trevi Fountain — The Most Famous Fountain in the World',
      'order'       => 5,
      'location'    => ['lat' => 41.9009, 'lng' => 12.4833],
      'description' => 'Complete your Roman journey at the Trevi Fountain — the Fontana di Trevi — the largest Baroque fountain in Rome and the most famous fountain in the world. Built into the back wall of Palazzo Poli, the fountain was designed by Nicola Salvi and completed in 1762, nearly three centuries after Pope Nicholas V first commissioned a new terminal fountain for the ancient Acqua Vergine aqueduct in 1453. The central figure is Neptune, god of the sea, riding a shell-shaped chariot pulled by two sea horses — one calm, one wild — guided by Tritons, representing the sea in different moods. The theatrical composition, with figures carved from Carrara marble against a triumphal arch backdrop, is a masterpiece of the late Baroque style. The tradition of throwing a coin into the fountain — which guarantees a return to Rome — was popularised by the 1954 film Three Coins in the Fountain and immortalised by Federico Fellini\'s La Dolce Vita in 1960, in which Anita Ekberg wades through the fountain in an iconic scene. Today approximately €3,000 worth of coins are thrown into the fountain every day — all collected nightly by the city authorities and donated to a charity that provides food for Rome\'s poor. Arrive very early in the morning (before 7am) to experience the fountain without crowds and to see the beautiful play of light on the water and marble in the golden morning sunshine.',
      'translations' => [
        'es' => ['title' => 'Fontana di Trevi — la fuente más famosa del mundo', 'description' => 'Complete su recorrido romano en la Fontana di Trevi, la mayor fuente barroca de Roma y la más famosa del mundo. Diseñada por Nicola Salvi y completada en 1762, la figura central es Neptuno sobre un carro en forma de concha tirado por dos caballos marinos — uno tranquilo, uno salvaje — guiados por tritones. La tradición de lanzar una moneda a la fuente — que garantiza el regreso a Roma — fue popularizada por la película Tres Monedas en la Fuente (1954) e inmortalizada por Fellini en La Dolce Vita (1960). Cada día se lanzan monedas por valor de unos 3.000€, recogidas nocturnamente y donadas a una organización benéfica. Llegue antes de las 7h para disfrutarla sin aglomeraciones.'],
        'fr' => ['title' => 'La Fontaine de Trevi — la plus célèbre fontaine du monde', 'description' => 'Terminez votre parcours romain à la Fontaine de Trevi, la plus grande fontaine baroque de Rome et la plus célèbre au monde. Conçue par Nicola Salvi et achevée en 1762, la figure centrale est Neptune sur un char en forme de coquille tiré par deux chevaux marins — l\'un calme, l\'autre sauvage — guidés par des Tritons. La tradition de lancer une pièce dans la fontaine — qui garantit un retour à Rome — a été popularisée par le film Trois pièces dans la fontaine (1954) et immortalisée par Fellini dans La Dolce Vita (1960). Chaque jour, environ 3 000€ de pièces sont lancées, collectées chaque nuit et données à une association caritative. Arrivez avant 7h pour en profiter sans foule.'],
        'de' => ['title' => 'Trevi-Brunnen — der berühmteste Brunnen der Welt', 'description' => 'Beenden Sie Ihre römische Reise am Trevi-Brunnen — dem größten Barockbrunnen Roms und dem berühmtesten Brunnen der Welt. Von Nicola Salvi entworfen und 1762 vollendet, zeigt die zentrale Figur Neptun auf einem muschelförmigen Wagen, gezogen von zwei Seepferden — einem ruhigen, einem wilden — geführt von Tritonen. Die Tradition, eine Münze in den Brunnen zu werfen — die eine Rückkehr nach Rom garantiert — wurde durch den Film Drei Münzen im Brunnen (1954) populär und durch Fellinis La Dolce Vita (1960) verewigt. Täglich werden Münzen im Wert von etwa 3.000€ hineingeworfen, nachts gesammelt und an eine Wohltätigkeitsorganisation gespendet. Kommen Sie vor 7 Uhr für ein Erlebnis ohne Menschenmassen.'],
        'it' => ['title' => 'Fontana di Trevi — la fontana più famosa del mondo', 'description' => 'Concludete il vostro viaggio romano alla Fontana di Trevi, la più grande fontana barocca di Roma e la più famosa al mondo. Progettata da Nicola Salvi e completata nel 1762, la figura centrale è Nettuno su un cocchio a forma di conchiglia trainato da due cavalli marini — uno calmo, uno selvaggio — guidati da tritoni. La tradizione di gettare una moneta nella fontana — che garantisce il ritorno a Roma — fu resa popolare dal film Tre soldi nella fontana (1954) e immortalata da Fellini ne La Dolce Vita (1960). Ogni giorno vengono gettate monete per circa 3.000€, raccolte ogni notte e donate in beneficenza. Arrivate prima delle 7 per godervi la fontana senza folla.'],
      ],
    ],
  ],
];
